In [121]:
import pandas as pd
# from sqlalchemy import create_engine
# connection_string = 'postgresql' + '://' + 'buddyadmin' + ':' + \
#                     'fintechbuddy' + '@' + 'postgres-buddy.ctzb27aixti7.ap-southeast-1.rds.amazonaws.com:5432' + '/' + \
#                     'buddymldb'
# engine = create_engine(connection_string)

In [122]:
df = pd.read_csv('referral_network.csv')

In [123]:
df.shape

(13226, 7)

In [124]:
df.head()

user_uuid                          network_uuid  \
0  f7633360-f9b1-11e6-a9c5-4f0b16583440  5d745180-f9c0-11e6-8558-8f833f3076cd   
1  f7633360-f9b1-11e6-a9c5-4f0b16583440  31622790-fdab-11e6-89b6-5ff7811f812a   
2                            8105682408                            7760810397   
3                            8105682408                            7829833982   
4                            8105682408                            9845075927   

   network_id  user_credit_score  network_credit_score  network_loan_amount  \
0           3         664.116614            603.549948              23500.0   
1           3         664.116614            605.259469               4000.0   
2           3         642.989050            785.345391              48360.0   
3           3         642.989050            784.107971              57615.0   
4           3         642.989050            651.418879                  0.0   

   network_order_count  
0                  7.0  
1                  2.0  
2                 34.0  
3                152.0  
4                  0.0

In [125]:
df.head()

user_uuid                          network_uuid  \
0  f7633360-f9b1-11e6-a9c5-4f0b16583440  5d745180-f9c0-11e6-8558-8f833f3076cd   
1  f7633360-f9b1-11e6-a9c5-4f0b16583440  31622790-fdab-11e6-89b6-5ff7811f812a   
2                            8105682408                            7760810397   
3                            8105682408                            7829833982   
4                            8105682408                            9845075927   

   network_id  user_credit_score  network_credit_score  network_loan_amount  \
0           3         664.116614            603.549948              23500.0   
1           3         664.116614            605.259469               4000.0   
2           3         642.989050            785.345391              48360.0   
3           3         642.989050            784.107971              57615.0   
4           3         642.989050            651.418879                  0.0   

   network_order_count  
0                  7.0  
1                  2.0  
2                 34.0  
3                152.0  
4                  0.0

In [126]:
df['network_loan_amount']==0
resultant_df = df[df['network_loan_amount'] != 0]
resultant_df.shape

(10519, 7)

In [127]:
resultant_df.shape
# df.user_uuid.value_counts() > 1

(10519, 7)

In [128]:
import numpy as np
grouped=resultant_df.groupby('user_uuid')
g_wavg= lambda x: np.average(x.network_credit_score, weights=x.network_loan_amount)
group_cs = grouped.apply(g_wavg)

# df.head()

In [129]:
final_df = pd.DataFrame(group_cs)

In [130]:
final_df.reset_index(level=0,inplace=True)
final_df.to_csv('cumulative.csv')

In [136]:
# final_df.head()
data_df = pd.merge(resultant_df,final_df,how="left",on="user_uuid")

In [137]:
data_df.head()

user_uuid                          network_uuid  \
0  f7633360-f9b1-11e6-a9c5-4f0b16583440  5d745180-f9c0-11e6-8558-8f833f3076cd   
1  f7633360-f9b1-11e6-a9c5-4f0b16583440  31622790-fdab-11e6-89b6-5ff7811f812a   
2                            8105682408                            7760810397   
3                            8105682408                            7829833982   
4                            8553229080  5504b750-e1ed-11e6-b685-7942eecceaad   

   network_id  user_credit_score  network_credit_score  network_loan_amount  \
0           3         664.116614            603.549948              23500.0   
1           3         664.116614            605.259469               4000.0   
2           3         642.989050            785.345391              48360.0   
3           3         642.989050            784.107971              57615.0   
4           3         608.350119            799.981096              20000.0   

   network_order_count           0  
0                  7.0  603.798606  
1                  2.0  603.798606  
2                 34.0  784.672648  
3                152.0  784.672648  
4                  2.0  797.565962

In [138]:
data_df.head()

user_uuid                          network_uuid  \
0  f7633360-f9b1-11e6-a9c5-4f0b16583440  5d745180-f9c0-11e6-8558-8f833f3076cd   
1  f7633360-f9b1-11e6-a9c5-4f0b16583440  31622790-fdab-11e6-89b6-5ff7811f812a   
2                            8105682408                            7760810397   
3                            8105682408                            7829833982   
4                            8553229080  5504b750-e1ed-11e6-b685-7942eecceaad   

   network_id  user_credit_score  network_credit_score  network_loan_amount  \
0           3         664.116614            603.549948              23500.0   
1           3         664.116614            605.259469               4000.0   
2           3         642.989050            785.345391              48360.0   
3           3         642.989050            784.107971              57615.0   
4           3         608.350119            799.981096              20000.0   

   network_order_count           0  
0                  7.0  603.798606  
1                  2.0  603.798606  
2                 34.0  784.672648  
3                152.0  784.672648  
4                  2.0  797.565962

In [140]:
data_df = data_df[['user_uuid','user_credit_score',0]]

In [142]:
data_df.rename(columns={0:'cumulative_network_cs'})

user_uuid  user_credit_score  \
0      f7633360-f9b1-11e6-a9c5-4f0b16583440         664.116614   
1      f7633360-f9b1-11e6-a9c5-4f0b16583440         664.116614   
2                                8105682408         642.989050   
3                                8105682408         642.989050   
4                                8553229080         608.350119   
5                                8553229080         608.350119   
6                                8553229080         608.350119   
7                                8553229080         608.350119   
8                                7275084496         799.989611   
9                                7275084496         799.989611   
10                               7275084496         799.989611   
11                               7275084496         799.989611   
12                               7275084496         799.989611   
13                               7275084496         799.989611   
14                               7275084496         799.989611   
15                               7275084496         799.989611   
16                               7275084496         799.989611   
17                               7275084496         799.989611   
18                               7275084496         799.989611   
19                               7275084496         799.989611   
20                               7275084496         799.989611   
21                               7275084496         799.989611   
22                               7275084496         799.989611   
23                               7275084496         799.989611   
24                               7275084496         799.989611   
25                               7275084496         799.989611   
26                               7275084496         799.989611   
27                               7275084496         799.989611   
28                               7275084496         799.989611   
29                               7275084496         799.989611   
...                                     ...                ...   
10489                            8553732931         607.999017   
10490                            8553732931         607.999017   
10491  59d23470-2837-11e7-9d70-a9f74712d401         799.988640   
10492  367903d0-d807-11e6-9f02-55bfbead9d00         798.452916   
10493  367903d0-d807-11e6-9f02-55bfbead9d00         798.452916   
10494  367903d0-d807-11e6-9f02-55bfbead9d00         798.452916   
10495  367903d0-d807-11e6-9f02-55bfbead9d00         798.452916   
10496  367903d0-d807-11e6-9f02-55bfbead9d00         798.452916   
10497  367903d0-d807-11e6-9f02-55bfbead9d00         798.452916   
10498  367903d0-d807-11e6-9f02-55bfbead9d00         798.452916   
10499  367903d0-d807-11e6-9f02-55bfbead9d00         798.452916   
10500  367903d0-d807-11e6-9f02-55bfbead9d00         798.452916   
10501  367903d0-d807-11e6-9f02-55bfbead9d00         798.452916   
10502  a88c5210-09ad-11e7-b7d3-87109c3be552         798.933729   
10503  8168e510-20ee-11e7-b2b0-ab92f3e5b5d8         799.661178   
10504  de0f7d90-1245-11e7-9d96-e9cdeb4076fc         790.896485   
10505  de0f7d90-1245-11e7-9d96-e9cdeb4076fc         790.896485   
10506  de0f7d90-1245-11e7-9d96-e9cdeb4076fc         790.896485   
10507  de0f7d90-1245-11e7-9d96-e9cdeb4076fc         790.896485   
10508  de0f7d90-1245-11e7-9d96-e9cdeb4076fc         790.896485   
10509  de0f7d90-1245-11e7-9d96-e9cdeb4076fc         790.896485   
10510  de0f7d90-1245-11e7-9d96-e9cdeb4076fc         790.896485   
10511  de0f7d90-1245-11e7-9d96-e9cdeb4076fc         790.896485   
10512  6c9e57b0-4113-11e7-8954-3dd362feb293         799.980282   
10513  a756b150-3a0a-11e7-8604-85352cd80e04         799.684657   
10514  a1c8b170-115b-11e7-9d96-e9cdeb4076fc         651.692636   
10515  a100ed70-de3e-11e6-aa79-1bde32099ed8         799.999622   
10516  632ec500-f7f0-11e6-9a0a-89e8b7c29667         607.818295   
10517  35568730-398b-11e7-8604-85352cd80e04         774.954514   
10518  3

In [143]:
# fin_df = data_df.duplicated('user_uuid', keep='first')

In [150]:
fin_df = data_df.loc[~data_df.duplicated('user_uuid', keep='first'),:]

In [152]:
fin_df.shape

(4131, 3)

In [157]:
from sklearn.linear_model import LinearRegression

In [158]:
linReg = LinearRegression()

In [159]:
linReg

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [164]:
fin_df.rename(columns={0:'cumulative_cs'}, inplace=True)

/Library/Python/2.7/site-packages/pandas/core/frame.py:2834: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  **kwargs)


In [165]:
fin_df.head()

user_uuid  user_credit_score  cumulative_cs
0   f7633360-f9b1-11e6-a9c5-4f0b16583440         664.116614     603.798606
2                             8105682408         642.989050     784.672648
4                             8553229080         608.350119     797.565962
8                             7275084496         799.989611     766.289744
31                            9538500840         782.150195     729.691605

In [205]:
fin_df = fin_df.dropna()
# fin_df.to_csv('final_ref_model.csv')
X = fin_df['cumulative_cs']

In [206]:
y = fin_df['user_credit_score']

In [207]:
type(X)
# y.shape
# linReg.fit(X,y)

pandas.core.series.Series

In [208]:
# X = pd.Series.as_matrix(X)
# y = pd.Series.as_matrix(y)


In [214]:
import numpy as np
X = X.reshape(len(X),1)
y = y.reshape(len(y),1)
# linReg.fit(X,y)

/Library/Python/2.7/site-packages/ipykernel/__main__.py:3: FutureWarning: reshape is deprecated and will raise in a subsequent release. Please use .values.reshape(...) instead
  app.launch_new_instance()


In [215]:
y.shape
# linReg.fit(X,y)
#  f = X.reshape(4080,1)

(4080, 1)

In [234]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.4)
X_train.shape
linReg.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [235]:
linReg.coef_

array([[ 0.27081936]])

In [236]:
linReg.intercept_

array([ 543.92160149])

In [243]:
y_pred = linReg.predict(X_test)
# linReg.predict([600,1])

In [249]:
# y_test.shape
y_pred.shape
from sklearn import metrics
print (metrics.mean_squared_error(y_test, y_pred))
# linReg.predict([[600]])

6073.29871364


In [225]:
# linReg.predict([[650]])

array([[ 717.14680807]])